USE [TADWH]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 13.01.2026 10:54:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[CustomerId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[SearchName] [nvarchar](200) NOT NULL,
	[Name2] [nvarchar](100) NOT NULL,
	[Address] [nvarchar](200) NOT NULL,
	[Address2] [nvarchar](100) NOT NULL,
	[City] [nvarchar](60) NOT NULL,
	[Contact] [nvarchar](200) NOT NULL,
	[PhoneNo] [nvarchar](60) NOT NULL,
	[TelexNo] [nvarchar](40) NOT NULL,
	[DocumentSendingProfile] [nvarchar](40) NOT NULL,
	[ShiptoCode] [nvarchar](20) NOT NULL,
	[OurAccountNo] [nvarchar](40) NOT NULL,
	[TerritoryCode] [nvarchar](20) NOT NULL,
	[GlobalDimension1Code] [nvarchar](40) NOT NULL,
	[GlobalDimension2Code] [nvarchar](40) NOT NULL,
	[ChainName] [nvarchar](20) NOT NULL,
	[BudgetedAmount] [decimal](38, 20) NOT NULL,
	[CreditLimitLCY] [decimal](38, 20) NOT NULL,
	[CustomerPostingGroup] [nvarchar](40) NOT NULL,
	[CurrencyCode] [nvarchar](20) NOT NULL,
	[CustomerPriceGroup] [nvarchar](20) NOT NULL,
	[LanguageCode] [nvarchar](20) NOT NULL,
	[StatisticsGroup] [int] NOT NULL,
	[PaymentTermsCode] [nvarchar](20) NOT NULL,
	[FinChargeTermsCode] [nvarchar](20) NOT NULL,
	[SalespersonCode] [nvarchar](40) NOT NULL,
	[ShipmentMethodCode] [nvarchar](20) NOT NULL,
	[ShippingAgentCode] [nvarchar](20) NOT NULL,
	[PlaceofExport] [nvarchar](40) NOT NULL,
	[InvoiceDiscCode] [nvarchar](40) NOT NULL,
	[CustomerDiscGroup] [nvarchar](40) NOT NULL,
	[CountryRegionCode] [nvarchar](20) NOT NULL,
	[CollectionMethod] [nvarchar](40) NOT NULL,
	[Amount] [decimal](38, 20) NOT NULL,
	[Blocked] [int] NOT NULL,
	[InvoiceCopies] [int] NOT NULL,
	[LastStatementNo] [int] NOT NULL,
	[PrintStatements] [tinyint] NOT NULL,
	[BilltoCustomerNo] [nvarchar](40) NOT NULL,
	[Priority] [int] NOT NULL,
	[PaymentMethodCode] [nvarchar](20) NOT NULL,
	[LastModifiedDateTime] [datetime] NOT NULL,
	[LastDateModified] [datetime] NOT NULL,
	[ApplicationMethod] [int] NOT NULL,
	[PricesIncludingVAT] [tinyint] NOT NULL,
	[LocationCode] [nvarchar](20) NOT NULL,
	[FaxNo] [nvarchar](60) NOT NULL,
	[TelexAnswerBack] [nvarchar](40) NOT NULL,
	[VATRegistrationNo] [nvarchar](40) NOT NULL,
	[CombineShipments] [tinyint] NOT NULL,
	[GenBusPostingGroup] [nvarchar](40) NOT NULL,
	[Picture] [image] NULL,
	[GLN] [nvarchar](26) NOT NULL,
	[PostCode] [nvarchar](40) NOT NULL,
	[County] [nvarchar](60) NOT NULL,
	[EORINumber] [nvarchar](80) NOT NULL,
	[UseGLNinElectronicDocument] [tinyint] NOT NULL,
	[EMail] [nvarchar](160) NOT NULL,
	[HomePage] [nvarchar](160) NOT NULL,
	[ReminderTermsCode] [nvarchar](20) NOT NULL,
	[NoSeries] [nvarchar](40) NOT NULL,
	[TaxAreaCode] [nvarchar](40) NOT NULL,
	[TaxLiable] [tinyint] NOT NULL,
	[VATBusPostingGroup] [nvarchar](40) NOT NULL,
	[Reserve] [int] NOT NULL,
	[BlockPaymentTolerance] [tinyint] NOT NULL,
	[ICPartnerCode] [nvarchar](40) NOT NULL,
	[PrepaymentPct] [decimal](38, 20) NOT NULL,
	[PartnerType] [int] NOT NULL,
	[Image] [uniqueidentifier] NOT NULL,
	[PrivacyBlocked] [tinyint] NOT NULL,
	[DisableSearchbyName] [tinyint] NOT NULL,
	[PreferredBankAccountCode] [nvarchar](40) NOT NULL,
	[CashFlowPaymentTermsCode] [nvarchar](20) NOT NULL,
	[PrimaryContactNo] [nvarchar](40) NOT NULL,
	[ContactType] [int] NOT NULL,
	[MobilePhoneNo] [nvarchar](60) NOT NULL,
	[ResponsibilityCenter] [nvarchar](20) NOT NULL,
	[ShippingAdvice] [int] NOT NULL,
	[ShippingTime] [nvarchar](32) NOT NULL,
	[ShippingAgentServiceCode] [nvarchar](20) NOT NULL,
	[ServiceZoneCode] [nvarchar](20) NOT NULL,
	[PriceCalculationMethod] [int] NOT NULL,
	[AllowLineDisc] [tinyint] NOT NULL,
	[BaseCalendarCode] [nvarchar](20) NOT NULL,
	[CopySelltoAddrtoQteFrom] [int] NOT NULL,
	[ValidateEUVatRegNo] [tinyint] NOT NULL,
	[OrigId] [uniqueidentifier] NOT NULL,
	[OrigCurrencyId] [uniqueidentifier] NOT NULL,
	[OrigPaymentTermsId] [uniqueidentifier] NOT NULL,
	[OrigShipmentMethodId] [uniqueidentifier] NOT NULL,
	[OrigPaymentMethodId] [uniqueidentifier] NOT NULL,
	[OrigTaxAreaID] [uniqueidentifier] NOT NULL,
	[OrigContactID] [uniqueidentifier] NOT NULL,
	[OrigContactGraphId] [nvarchar](500) NOT NULL,
	[systemId] [uniqueidentifier] NOT NULL,
	[systemCreatedAt] [datetime] NOT NULL,
	[systemCreatedBy] [uniqueidentifier] NOT NULL,
	[systemModifiedAt] [datetime] NOT NULL,
	[systemModifiedBy] [uniqueidentifier] NOT NULL,
	[IntrastatPartnerType] [int] NOT NULL,
	[CoupledtoCRM] [tinyint] NOT NULL,
	[RegistrationNumber] [nvarchar](100) NOT NULL,
	[FormatRegion] [nvarchar](160) NOT NULL,
	[ExcludefromPmtPractices] [tinyint] NOT NULL,
	[AllowMultiplePostingGroups] [tinyint] NOT NULL,
	[OPPDDFollowUpLetterCode] [nvarchar](20) NULL,
	[OPPAssociationNo] [nvarchar](40) NULL,
	[OPPAssociationSortCode] [nvarchar](40) NULL,
	[OPPBalanceAcknowledgmtCode] [nvarchar](20) NULL,
	[OPPLastPostingat] [datetime] NULL,
	[OPPBalAckShippingAddress] [nvarchar](40) NULL,
	[OPPBalAckShippingType] [int] NULL,
	[OPPAdviceShippingType] [int] NULL,
	[OPPAdviceShippingAddress] [nvarchar](40) NULL,
	[OPPInstallmentTemplate] [nvarchar](20) NULL,
	[OPPInstallmentTemplateType] [int] NULL,
	[OPPValueDateCalculation] [nvarchar](32) NULL,
	[TACopyrightFeeRequired] [tinyint] NULL,
	[TARefundDisposalLumpSum] [tinyint] NULL,
	[TAOldCustomerNo] [nvarchar](40) NULL,
	[TAAssignedVendorNo] [nvarchar](40) NULL,
	[TAOriginalCustomerNo] [nvarchar](40) NULL,
	[TAStatisticsGroupCode] [nvarchar](40) NULL,
	[TACollection] [nvarchar](100) NULL,
	[TAARANecessary] [tinyint] NULL,
	[TASalesManagerCode] [nvarchar](20) NULL,
	[TASalesAreaCode] [nvarchar](40) NULL,
	[TAIntSalesRepresentativeCode] [nvarchar](40) NULL,
	[TAContractClerkCode] [nvarchar](40) NULL,
	[TAFInancialAccClerkCode] [nvarchar](40) NULL,
	[OrigTAExternalCRMID] [nvarchar](100) NULL,
	[TASubstituteCode] [nvarchar](40) NULL,
	[TACreditInsurerNo] [nvarchar](40) NULL,
	[TAInternalCustomerNo] [nvarchar](40) NULL,
	[TAUPSCustomerNo] [nvarchar](20) NULL,
	[TAExtDocNoRequiredVBM] [tinyint] NULL,
	[TAUseContractNoVBM] [tinyint] NULL,
	[TAYourRefRequiredService] [tinyint] NULL,
	[TAUseContractNoService] [tinyint] NULL,
	[TAUTAXSpecialistDealer] [tinyint] NULL,
	[TAAssociationMembershipNo] [nvarchar](40) NULL,
	[TAMISInternalExternal] [int] NULL,
	[TAMISDomesticForeign] [int] NULL,
	[TAMISBrand] [int] NULL,
	[TACustomerType] [int] NULL,
	[TAPrintSerialNoOnIvoice] [tinyint] NULL,
	[TAPrintMACAddrOnShipment] [tinyint] NULL,
	[TACombineShipmentService] [tinyint] NULL,
	[TACombineShipmentVBM] [tinyint] NULL,
	[TAServPostalInvRecipientCode] [nvarchar](20) NULL,
	[TAPostalBillToCode] [nvarchar](20) NULL,
	[TALabelPrintingOuterPackaging] [tinyint] NULL,
	[TACENecessaryVBM] [tinyint] NULL,
	[TACENecessaryService] [tinyint] NULL,
	[TAECMFlow] [tinyint] NULL,
	[TAIntercompany] [tinyint] NULL,
	[TADistributionChannel] [nvarchar](40) NULL,
	[TARequestEntryNo] [int] NULL,
	[TAWorkflowTeam] [nvarchar](20) NULL,
	[TACreationUser] [nvarchar](100) NULL,
	[TAModificationUser] [nvarchar](100) NULL,
	[TAInterfacePartnerNo] [nvarchar](40) NULL,
	[TAIgnoreOrderTypeLayout] [tinyint] NULL,
	[TATariffNoOnInvoice] [tinyint] NULL,
	[TACountryOfOriginOnInvoice] [tinyint] NULL,
	[TASendDeviceDataToKFS] [tinyint] NULL,
	[TAInternationalDataProtAgrmnt] [tinyint] NULL,
	[TAXRechActive] [tinyint] NULL,
	[OrigTAXRechPeppolID] [nvarchar](500) NULL,
	[TAXRechEmail] [nvarchar](500) NULL,
	[TAWkfStatus] [int] NULL,
	[TAInterfaceTimestamp] [datetime] NULL,
	[DefaultTransType] [nvarchar](20) NULL,
	[DefaultTransTypeReturn] [nvarchar](20) NULL,
	[DefTransportMethod] [nvarchar](20) NULL,
	[OPPCreditInsuranceNo] [nvarchar](40) NULL,
	[OPPExternalCreditLimit] [decimal](38, 20) NULL,
	[AddressId] [bigint] NOT NULL,
	[TerritoryId] [bigint] NOT NULL,
	[CustomerPostingGroupId] [bigint] NOT NULL,
	[CustomerPriceGroupId] [bigint] NOT NULL,
	[PaymentTermsId] [bigint] NOT NULL,
	[SalespersonId] [bigint] NOT NULL,
	[ShipmentMethodId] [bigint] NOT NULL,
	[CustomerDiscountGroupId] [bigint] NOT NULL,
	[CountryRegionId] [bigint] NOT NULL,
	[PaymentMethodId] [bigint] NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[GenBusinessPostingGroupId] [bigint] NOT NULL,
	[VATBusinessPostingGroupId] [bigint] NOT NULL,
	[ResponsibilityCenterId] [bigint] NOT NULL,
	[TAStatisticsGroupId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
 CONSTRAINT [pk_dbo_Customer_CustomerId] PRIMARY KEY NONCLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customer] ADD  CONSTRAINT [df_dbo_Customer_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[Customer] ADD  CONSTRAINT [df_dbo_Customer_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[Customer] ADD  CONSTRAINT [df_dbo_Customer_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


