USE [TADWH]
GO

/****** Object:  Table [dbo].[PurchCrMemoLine]    Script Date: 20.01.2026 11:04:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PurchCrMemoLine](
	[PurchCrMemoLineId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[DocumentNo] [nvarchar](40) NOT NULL,
	[LineNo] [int] NOT NULL,
	[BuyfromVendorNo] [nvarchar](40) NOT NULL,
	[Type] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[LocationCode] [nvarchar](20) NOT NULL,
	[PostingGroup] [nvarchar](40) NOT NULL,
	[ExpectedReceiptDate] [datetime] NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Description2] [nvarchar](100) NOT NULL,
	[UnitofMeasure] [nvarchar](100) NOT NULL,
	[Quantity] [decimal](38, 20) NOT NULL,
	[DirectUnitCost] [decimal](38, 20) NOT NULL,
	[UnitCostLCY] [decimal](38, 20) NOT NULL,
	[VATPct] [decimal](38, 20) NOT NULL,
	[LineDiscountPct] [decimal](38, 20) NOT NULL,
	[LineDiscountAmount] [decimal](38, 20) NOT NULL,
	[Amount] [decimal](38, 20) NOT NULL,
	[AmountIncludingVAT] [decimal](38, 20) NOT NULL,
	[UnitPriceLCY] [decimal](38, 20) NOT NULL,
	[AllowInvoiceDisc] [tinyint] NOT NULL,
	[GrossWeight] [decimal](38, 20) NOT NULL,
	[NetWeight] [decimal](38, 20) NOT NULL,
	[UnitsperParcel] [decimal](38, 20) NOT NULL,
	[UnitVolume] [decimal](38, 20) NOT NULL,
	[AppltoItemEntry] [int] NOT NULL,
	[ShortcutDimension1Code] [nvarchar](40) NOT NULL,
	[ShortcutDimension2Code] [nvarchar](40) NOT NULL,
	[JobNo] [nvarchar](40) NOT NULL,
	[IndirectCostPct] [decimal](38, 20) NOT NULL,
	[OrderNo] [nvarchar](40) NOT NULL,
	[OrderLineNo] [int] NOT NULL,
	[PaytoVendorNo] [nvarchar](40) NOT NULL,
	[InvDiscountAmount] [decimal](38, 20) NOT NULL,
	[VendorItemNo] [nvarchar](100) NOT NULL,
	[GenBusPostingGroup] [nvarchar](40) NOT NULL,
	[GenProdPostingGroup] [nvarchar](40) NOT NULL,
	[VATCalculationType] [int] NOT NULL,
	[TransactionType] [nvarchar](20) NOT NULL,
	[TransportMethod] [nvarchar](20) NOT NULL,
	[AttachedtoLineNo] [int] NOT NULL,
	[EntryPoint] [nvarchar](20) NOT NULL,
	[Area] [nvarchar](20) NOT NULL,
	[TransactionSpecification] [nvarchar](20) NOT NULL,
	[TaxAreaCode] [nvarchar](40) NOT NULL,
	[TaxLiable] [tinyint] NOT NULL,
	[TaxGroupCode] [nvarchar](40) NOT NULL,
	[UseTax] [tinyint] NOT NULL,
	[VATBusPostingGroup] [nvarchar](40) NOT NULL,
	[VATProdPostingGroup] [nvarchar](40) NOT NULL,
	[BlanketOrderNo] [nvarchar](40) NOT NULL,
	[BlanketOrderLineNo] [int] NOT NULL,
	[VATBaseAmount] [decimal](38, 20) NOT NULL,
	[UnitCost] [decimal](38, 20) NOT NULL,
	[SystemCreatedEntry] [tinyint] NOT NULL,
	[LineAmount] [decimal](38, 20) NOT NULL,
	[VATDifference] [decimal](38, 20) NOT NULL,
	[VATIdentifier] [nvarchar](40) NOT NULL,
	[ICPartnerRefType] [int] NOT NULL,
	[ICPartnerReference] [nvarchar](40) NOT NULL,
	[PrepaymentLine] [tinyint] NOT NULL,
	[ICPartnerCode] [nvarchar](40) NOT NULL,
	[PostingDate] [datetime] NOT NULL,
	[ICItemReferenceNo] [nvarchar](100) NOT NULL,
	[PmtDiscountAmount] [decimal](38, 20) NOT NULL,
	[OrigDimensionSetID] [int] NOT NULL,
	[JobTaskNo] [nvarchar](40) NOT NULL,
	[JobLineType] [int] NOT NULL,
	[JobUnitPrice] [decimal](38, 20) NOT NULL,
	[JobTotalPrice] [decimal](38, 20) NOT NULL,
	[JobLineAmount] [decimal](38, 20) NOT NULL,
	[JobLineDiscountAmount] [decimal](38, 20) NOT NULL,
	[JobLineDiscountPct] [decimal](38, 20) NOT NULL,
	[JobUnitPriceLCY] [decimal](38, 20) NOT NULL,
	[JobTotalPriceLCY] [decimal](38, 20) NOT NULL,
	[JobLineAmountLCY] [decimal](38, 20) NOT NULL,
	[JobLineDiscAmountLCY] [decimal](38, 20) NOT NULL,
	[JobCurrencyFactor] [decimal](38, 20) NOT NULL,
	[JobCurrencyCode] [nvarchar](40) NOT NULL,
	[DeferralCode] [nvarchar](20) NOT NULL,
	[ProdOrderNo] [nvarchar](40) NOT NULL,
	[VariantCode] [nvarchar](20) NOT NULL,
	[BinCode] [nvarchar](40) NOT NULL,
	[QtyperUnitofMeasure] [decimal](38, 20) NOT NULL,
	[UnitofMeasureCode] [nvarchar](20) NOT NULL,
	[QuantityBase] [decimal](38, 20) NOT NULL,
	[FAPostingDate] [datetime] NOT NULL,
	[FAPostingType] [int] NOT NULL,
	[DepreciationBookCode] [nvarchar](20) NOT NULL,
	[SalvageValue] [decimal](38, 20) NOT NULL,
	[DepruntilFAPostingDate] [tinyint] NOT NULL,
	[DeprAcquisitionCost] [tinyint] NOT NULL,
	[MaintenanceCode] [nvarchar](20) NOT NULL,
	[InsuranceNo] [nvarchar](40) NOT NULL,
	[BudgetedFANo] [nvarchar](40) NOT NULL,
	[DuplicateinDepreciationBook] [nvarchar](20) NOT NULL,
	[UseDuplicationList] [tinyint] NOT NULL,
	[ResponsibilityCenter] [nvarchar](20) NOT NULL,
	[CrossReferenceNo] [nvarchar](40) NOT NULL,
	[UnitofMeasureCrossRef] [nvarchar](20) NOT NULL,
	[CrossReferenceType] [int] NOT NULL,
	[CrossReferenceTypeNo] [nvarchar](60) NOT NULL,
	[ItemCategoryCode] [nvarchar](40) NOT NULL,
	[Nonstock] [tinyint] NOT NULL,
	[PurchasingCode] [nvarchar](20) NOT NULL,
	[ProductGroupCode] [nvarchar](20) NOT NULL,
	[ItemReferenceNo] [nvarchar](100) NOT NULL,
	[ItemReferenceUnitofMeasure] [nvarchar](20) NOT NULL,
	[ItemReferenceType] [int] NOT NULL,
	[ItemReferenceTypeNo] [nvarchar](60) NOT NULL,
	[ReturnShipmentNo] [nvarchar](40) NOT NULL,
	[ReturnShipmentLineNo] [int] NOT NULL,
	[ReturnReasonCode] [nvarchar](20) NOT NULL,
	[PriceCalculationMethod] [int] NOT NULL,
	[OrderNoOld] [nvarchar](40) NOT NULL,
	[OrderLineNoOld] [int] NOT NULL,
	[NonDeductibleVATPct] [decimal](38, 20) NOT NULL,
	[NonDeductibleVATBase] [decimal](38, 20) NOT NULL,
	[NonDeductibleVATAmount] [decimal](38, 20) NOT NULL,
	[NonDeductibleVATDiff] [decimal](38, 20) NOT NULL,
	[TAPositionNo] [int] NULL,
	[TAOriginalItemNo] [nvarchar](40) NULL,
	[TACustomerOrderNumber] [nvarchar](70) NULL,
	[TABLNo] [nvarchar](60) NULL,
	[OrigTAContainerID] [nvarchar](40) NULL,
	[TABillOfLadingNo] [nvarchar](40) NULL,
	[TABillOfLadingLineNo] [int] NULL,
	[TABillOfLadingDetailLineNo] [int] NULL,
	[TABillOfLadingOrderLineNo] [int] NULL,
	[TAKDCInvoiceNo] [nvarchar](40) NULL,
	[TAKDCInvoiceLineNo] [nvarchar](20) NULL,
	[TAProjectNo] [nvarchar](40) NULL,
	[TASubProjectNo] [nvarchar](40) NULL,
	[TAProjectLineNo] [int] NULL,
	[TAServiceItemNo] [nvarchar](40) NULL,
	[TAServiceItemDescription] [nvarchar](200) NULL,
	[TAServiceItemSerialNo] [nvarchar](100) NULL,
	[TAWorkpackageCode] [nvarchar](40) NULL,
	[TAWorkpackageLineNo] [int] NULL,
	[TATonerSupportCode] [nvarchar](40) NULL,
	[TAFromIncomingPurchLine] [tinyint] NULL,
	[TAExternalLineNo] [int] NULL,
	[TACustomerLabelInformation1] [nvarchar](400) NULL,
	[TACustomerLabelInformation2] [nvarchar](400) NULL,
	[TACustomerLabelInformation3] [nvarchar](400) NULL,
	[TAPitchContactName] [nvarchar](200) NULL,
	[TACustomerObjectPosNo] [nvarchar](100) NULL,
	[TAExternalCostCenter] [nvarchar](60) NULL,
	[OrigTADeviceID] [nvarchar](100) NULL,
	[TALocationofServiceItem] [nvarchar](100) NULL,
	[TABuilding] [nvarchar](60) NULL,
	[TAFloor] [nvarchar](60) NULL,
	[TARoom] [nvarchar](60) NULL,
	[TASiteName] [nvarchar](200) NULL,
	[TASiteName2] [nvarchar](100) NULL,
	[TASiteAddress] [nvarchar](200) NULL,
	[TASiteAddress2] [nvarchar](100) NULL,
	[TASiteCity] [nvarchar](60) NULL,
	[TASitePostCode] [nvarchar](40) NULL,
	[TASiteCounty] [nvarchar](60) NULL,
	[TASiteCountryRegionCode] [nvarchar](20) NULL,
	[TASiteServiceItemNo] [nvarchar](40) NULL,
	[TASiteServiceItemSerialNo] [nvarchar](100) NULL,
	[TASiteServiceItemDescr] [nvarchar](200) NULL,
	[BuyfromVendorId] [bigint] NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[AppltoItemLedgerEntryId] [bigint] NOT NULL,
	[JobId] [bigint] NOT NULL,
	[JobTaskId] [bigint] NOT NULL,
	[PaytoVendorId] [bigint] NOT NULL,
	[GenBusinessPostingGroupId] [bigint] NOT NULL,
	[GenProdPostingGroupId] [bigint] NOT NULL,
	[TransactionTypeId] [bigint] NOT NULL,
	[TransportMethodId] [bigint] NOT NULL,
	[AreaId] [bigint] NOT NULL,
	[VATBusinessPostingGroupId] [bigint] NOT NULL,
	[VATProductPostingGroupId] [bigint] NOT NULL,
	[BinId] [bigint] NOT NULL,
	[UnitofMeasureId] [bigint] NOT NULL,
	[ResponsibilityCenterId] [bigint] NOT NULL,
	[ItemCategoryId] [bigint] NOT NULL,
	[ProductGroupId] [bigint] NOT NULL,
	[ReturnShipmentHeaderId] [bigint] NOT NULL,
	[ReturnShipmentLineId] [bigint] NOT NULL,
	[ReturnReasonId] [bigint] NOT NULL,
	[TAProjectHeaderId] [bigint] NOT NULL,
	[TAProjectLineId] [bigint] NOT NULL,
	[TATonerSupportId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
	[systemId] [uniqueidentifier] NULL,
	[systemCreatedAt] [datetime] NULL,
	[systemCreatedBy] [uniqueidentifier] NULL,
	[systemModifiedAt] [datetime] NULL,
	[systemModifiedBy] [uniqueidentifier] NULL,
 CONSTRAINT [pk_dbo_PurchCrMemoLine_PurchCrMemoLineId] PRIMARY KEY NONCLUSTERED 
(
	[PurchCrMemoLineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PurchCrMemoLine] ADD  CONSTRAINT [df_dbo_PurchCrMemoLine_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[PurchCrMemoLine] ADD  CONSTRAINT [df_dbo_PurchCrMemoLine_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[PurchCrMemoLine] ADD  CONSTRAINT [df_dbo_PurchCrMemoLine_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


