USE [TADWH]
GO

/****** Object:  Table [dbo].[SalesInvoiceLine]    Script Date: 13.01.2026 10:53:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SalesInvoiceLine](
	[SalesInvoiceLineId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[DocumentNo] [nvarchar](40) NOT NULL,
	[LineNo] [int] NOT NULL,
	[SelltoCustomerNo] [nvarchar](40) NOT NULL,
	[Type] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[LocationCode] [nvarchar](20) NOT NULL,
	[PostingGroup] [nvarchar](40) NOT NULL,
	[ShipmentDate] [datetime] NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Description2] [nvarchar](100) NOT NULL,
	[UnitofMeasure] [nvarchar](100) NOT NULL,
	[Quantity] [decimal](38, 20) NOT NULL,
	[UnitPrice] [decimal](38, 20) NOT NULL,
	[UnitCostLCY] [decimal](38, 20) NOT NULL,
	[VATPct] [decimal](38, 20) NOT NULL,
	[LineDiscountPct] [decimal](38, 20) NOT NULL,
	[LineDiscountAmount] [decimal](38, 20) NOT NULL,
	[Amount] [decimal](38, 20) NOT NULL,
	[AmountIncludingVAT] [decimal](38, 20) NOT NULL,
	[AllowInvoiceDisc] [tinyint] NOT NULL,
	[GrossWeight] [decimal](38, 20) NOT NULL,
	[NetWeight] [decimal](38, 20) NOT NULL,
	[UnitsperParcel] [decimal](38, 20) NOT NULL,
	[UnitVolume] [decimal](38, 20) NOT NULL,
	[AppltoItemEntry] [int] NOT NULL,
	[ShortcutDimension1Code] [nvarchar](40) NOT NULL,
	[ShortcutDimension2Code] [nvarchar](40) NOT NULL,
	[CustomerPriceGroup] [nvarchar](20) NOT NULL,
	[JobNo] [nvarchar](40) NOT NULL,
	[WorkTypeCode] [nvarchar](20) NOT NULL,
	[ShipmentNo] [nvarchar](40) NOT NULL,
	[ShipmentLineNo] [int] NOT NULL,
	[OrderNo] [nvarchar](40) NOT NULL,
	[OrderLineNo] [int] NOT NULL,
	[BilltoCustomerNo] [nvarchar](40) NOT NULL,
	[InvDiscountAmount] [decimal](38, 20) NOT NULL,
	[DropShipment] [tinyint] NOT NULL,
	[GenBusPostingGroup] [nvarchar](40) NOT NULL,
	[GenProdPostingGroup] [nvarchar](40) NOT NULL,
	[VATCalculationType] [int] NOT NULL,
	[TransactionType] [nvarchar](20) NOT NULL,
	[TransportMethod] [nvarchar](20) NOT NULL,
	[AttachedtoLineNo] [int] NOT NULL,
	[ExitPoint] [nvarchar](20) NOT NULL,
	[Area] [nvarchar](20) NOT NULL,
	[TransactionSpecification] [nvarchar](20) NOT NULL,
	[TaxCategory] [nvarchar](20) NOT NULL,
	[TaxAreaCode] [nvarchar](40) NOT NULL,
	[TaxLiable] [tinyint] NOT NULL,
	[TaxGroupCode] [nvarchar](40) NOT NULL,
	[VATClauseCode] [nvarchar](40) NOT NULL,
	[VATBusPostingGroup] [nvarchar](40) NOT NULL,
	[VATProdPostingGroup] [nvarchar](40) NOT NULL,
	[BlanketOrderNo] [nvarchar](40) NOT NULL,
	[BlanketOrderLineNo] [int] NOT NULL,
	[VATBaseAmount] [decimal](38, 20) NOT NULL,
	[UnitCost] [decimal](38, 20) NOT NULL,
	[SystemCreatedEntry] [tinyint] NOT NULL,
	[LineAmount] [decimal](38, 20) NOT NULL,
	[VATDifference] [decimal](38, 20) NOT NULL,
	[VATIdentifier] [nvarchar](40) NOT NULL,
	[ICPartnerRefType] [int] NOT NULL,
	[ICPartnerReference] [nvarchar](40) NOT NULL,
	[PrepaymentLine] [tinyint] NOT NULL,
	[ICPartnerCode] [nvarchar](40) NOT NULL,
	[PostingDate] [datetime] NOT NULL,
	[ICItemReferenceNo] [nvarchar](100) NOT NULL,
	[PmtDiscountAmount] [decimal](38, 20) NOT NULL,
	[LineDiscountCalculation] [int] NOT NULL,
	[OrigDimensionSetID] [int] NOT NULL,
	[JobTaskNo] [nvarchar](40) NOT NULL,
	[JobContractEntryNo] [int] NOT NULL,
	[DeferralCode] [nvarchar](20) NOT NULL,
	[VariantCode] [nvarchar](20) NOT NULL,
	[BinCode] [nvarchar](40) NOT NULL,
	[QtyperUnitofMeasure] [decimal](38, 20) NOT NULL,
	[UnitofMeasureCode] [nvarchar](20) NOT NULL,
	[QuantityBase] [decimal](38, 20) NOT NULL,
	[FAPostingDate] [datetime] NOT NULL,
	[DepreciationBookCode] [nvarchar](20) NOT NULL,
	[DepruntilFAPostingDate] [tinyint] NOT NULL,
	[DuplicateinDepreciationBook] [nvarchar](20) NOT NULL,
	[UseDuplicationList] [tinyint] NOT NULL,
	[ResponsibilityCenter] [nvarchar](20) NOT NULL,
	[CrossReferenceNo] [nvarchar](40) NOT NULL,
	[UnitofMeasureCrossRef] [nvarchar](20) NOT NULL,
	[CrossReferenceType] [int] NOT NULL,
	[CrossReferenceTypeNo] [nvarchar](60) NOT NULL,
	[ItemCategoryCode] [nvarchar](40) NOT NULL,
	[Nonstock] [tinyint] NOT NULL,
	[PurchasingCode] [nvarchar](20) NOT NULL,
	[ProductGroupCode] [nvarchar](20) NOT NULL,
	[ItemReferenceNo] [nvarchar](100) NOT NULL,
	[ItemReferenceUnitofMeasure] [nvarchar](20) NOT NULL,
	[ItemReferenceType] [int] NOT NULL,
	[ItemReferenceTypeNo] [nvarchar](60) NOT NULL,
	[ApplfromItemEntry] [int] NOT NULL,
	[ReturnReasonCode] [nvarchar](20) NOT NULL,
	[PriceCalculationMethod] [int] NOT NULL,
	[AllowLineDisc] [tinyint] NOT NULL,
	[CustomerDiscGroup] [nvarchar](40) NOT NULL,
	[Pricedescription] [nvarchar](160) NOT NULL,
	[OrderNoOld] [nvarchar](40) NOT NULL,
	[OrderLineNoOld] [int] NOT NULL,
	[systemId] [uniqueidentifier] NOT NULL,
	[systemCreatedAt] [datetime] NOT NULL,
	[systemCreatedBy] [uniqueidentifier] NOT NULL,
	[systemModifiedAt] [datetime] NOT NULL,
	[systemModifiedBy] [uniqueidentifier] NOT NULL,
	[AllocationAccountNo] [nvarchar](40) NOT NULL,
	[TAPositionNo] [int] NOT NULL,
	[TABlanketOrderNo] [nvarchar](40) NOT NULL,
	[TABlanketOrderLineNo] [int] NOT NULL,
	[TAOriginalQtyBaseBlOrder] [decimal](38, 20) NOT NULL,
	[TAQtyBlOrderChangedFrom] [nvarchar](100) NOT NULL,
	[TARefundDisposalLumpSumInPerc] [decimal](38, 20) NOT NULL,
	[TACustomerItemDiscountInPerc] [decimal](38, 20) NOT NULL,
	[TAReasonZeroPrice] [nvarchar](20) NOT NULL,
	[TAQtyProformaInvoice] [decimal](38, 20) NOT NULL,
	[TAOriginalItemNo] [nvarchar](40) NOT NULL,
	[TAAttachedToLineNo2] [int] NOT NULL,
	[TAServiceItemNo] [nvarchar](40) NOT NULL,
	[TAServiceItemDescription] [nvarchar](200) NOT NULL,
	[TAPotentialItem] [tinyint] NOT NULL,
	[TAProcessingStatus] [int] NOT NULL,
	[TARMANo] [nvarchar](40) NOT NULL,
	[TAServiceItemSerialNo] [nvarchar](100) NOT NULL,
	[TAReturnErrorCode] [nvarchar](40) NOT NULL,
	[TARejectionReasonCode] [nvarchar](40) NOT NULL,
	[TACampaignNo] [nvarchar](40) NOT NULL,
	[TAItemType] [int] NOT NULL,
	[TAItemStatus] [int] NOT NULL,
	[TADecisionStatus] [int] NOT NULL,
	[TAReturnOrderNo] [nvarchar](40) NOT NULL,
	[TAReturnOrderLineNo] [int] NOT NULL,
	[TAInternalUnitPrice] [decimal](38, 20) NOT NULL,
	[TAInternalLineAmount] [decimal](38, 20) NOT NULL,
	[TAInternalLineDiscAmount] [decimal](38, 20) NOT NULL,
	[TAContractNo] [nvarchar](40) NOT NULL,
	[TAContractLineNo] [int] NOT NULL,
	[TAContingentCode] [nvarchar](40) NOT NULL,
	[TAProjectNo] [nvarchar](40) NOT NULL,
	[TAProjectLineNo] [int] NOT NULL,
	[TACockpitCode] [nvarchar](40) NOT NULL,
	[TAServiceItemCategory] [nvarchar](20) NOT NULL,
	[TAExternalDocumentNo] [nvarchar](70) NOT NULL,
	[TAErrorOverride] [tinyint] NOT NULL,
	[TALocationOfServiceItem] [nvarchar](60) NOT NULL,
	[TABuilding] [nvarchar](60) NOT NULL,
	[TAFloor] [nvarchar](60) NOT NULL,
	[TARoom] [nvarchar](60) NOT NULL,
	[TACombineShipmentVBM] [tinyint] NOT NULL,
	[OrigTAAssociatedCockpitBoxID] [nvarchar](100) NOT NULL,
	[TADistributionChannelCode] [nvarchar](40) NOT NULL,
	[TAAttachToServiceItemNo] [nvarchar](40) NOT NULL,
	[TASubProjectNo] [nvarchar](40) NOT NULL,
	[TACustPurchaseOrderNo] [nvarchar](40) NOT NULL,
	[TAPostedSalesShpNo] [nvarchar](40) NOT NULL,
	[TAPostedSalesShpLineNo] [int] NOT NULL,
	[TAPostedSalesShpDate] [datetime] NOT NULL,
	[TALineNotPrinting] [tinyint] NOT NULL,
	[TARegionalSalesMngPrice] [decimal](38, 20) NOT NULL,
	[TARepackaging] [tinyint] NOT NULL,
	[TATonerConsumption] [int] NOT NULL,
	[TACustomerLabelInformation1] [nvarchar](400) NOT NULL,
	[TACustomerLabelInformation2] [nvarchar](400) NOT NULL,
	[TACustomerLabelInformation3] [nvarchar](400) NOT NULL,
	[TAPitchContactName] [nvarchar](200) NOT NULL,
	[TACustomerObjectPosNo] [nvarchar](100) NOT NULL,
	[TAExternalCostCenter] [nvarchar](60) NOT NULL,
	[OrigTADeviceID] [nvarchar](100) NOT NULL,
	[TAExternalLineNo] [int] NOT NULL,
	[TASiteName] [nvarchar](200) NOT NULL,
	[TASiteName2] [nvarchar](100) NOT NULL,
	[TASiteAddress] [nvarchar](200) NOT NULL,
	[TASiteAddress2] [nvarchar](100) NOT NULL,
	[TASiteCity] [nvarchar](60) NOT NULL,
	[TASitePostCode] [nvarchar](40) NOT NULL,
	[TASiteCounty] [nvarchar](60) NOT NULL,
	[TASiteCountryRegionCode] [nvarchar](20) NOT NULL,
	[TASiteServiceItemNo] [nvarchar](40) NOT NULL,
	[TASiteServiceItemSerialNo] [nvarchar](100) NOT NULL,
	[TASiteServiceItemDescr] [nvarchar](200) NOT NULL,
	[TAShippingAgentCode] [nvarchar](20) NOT NULL,
	[TAShippingAgentServiceCode] [nvarchar](20) NOT NULL,
	[TAShippedVendorItemNo] [nvarchar](40) NOT NULL,
	[SelltoCustomerId] [bigint] NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[AppltoItemLedgerEntryId] [bigint] NOT NULL,
	[CustomerPriceGroupId] [bigint] NOT NULL,
	[JobId] [bigint] NOT NULL,
	[JobTaskId] [bigint] NOT NULL,
	[WorkTypeId] [bigint] NOT NULL,
	[SalesShipmentHeaderId] [bigint] NOT NULL,
	[SalesShipmentLineId] [bigint] NOT NULL,
	[BilltoCustomerId] [bigint] NOT NULL,
	[GenBusinessPostingGroupId] [bigint] NOT NULL,
	[GenProdPostingGroupId] [bigint] NOT NULL,
	[TransactionTypeId] [bigint] NOT NULL,
	[TransportMethodId] [bigint] NOT NULL,
	[AreaId] [bigint] NOT NULL,
	[VATBusinessPostingGroupId] [bigint] NOT NULL,
	[VATProductPostingGroupId] [bigint] NOT NULL,
	[BinId] [bigint] NOT NULL,
	[UnitofMeasureId] [bigint] NOT NULL,
	[ResponsibilityCenterId] [bigint] NOT NULL,
	[ItemCategoryId] [bigint] NOT NULL,
	[ProductGroupId] [bigint] NOT NULL,
	[ApplfromItemLedgerEntryId] [bigint] NOT NULL,
	[ReturnReasonId] [bigint] NOT NULL,
	[CustomerDiscountGroupId] [bigint] NOT NULL,
	[TAReasonForRejectionId] [bigint] NOT NULL,
	[TAContractHeaderId] [bigint] NOT NULL,
	[TAContractLineId] [bigint] NOT NULL,
	[TACtrContingentId] [bigint] NOT NULL,
	[TAProjectHeaderId] [bigint] NOT NULL,
	[TAProjectLineId] [bigint] NOT NULL,
	[TACockpitCodeId] [bigint] NOT NULL,
	[TAServiceItemCategoryId] [bigint] NOT NULL,
	[TADistributionChannelId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
 CONSTRAINT [pk_dbo_SalesInvoiceLine_SalesInvoiceLineId] PRIMARY KEY NONCLUSTERED 
(
	[SalesInvoiceLineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SalesInvoiceLine] ADD  CONSTRAINT [df_dbo_SalesInvoiceLine_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[SalesInvoiceLine] ADD  CONSTRAINT [df_dbo_SalesInvoiceLine_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[SalesInvoiceLine] ADD  CONSTRAINT [df_dbo_SalesInvoiceLine_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


