CREATE VIEW [Setting].[vColumn]
	AS SELECT a.[VersionId]
	  ,DB.[DBId] 
	  ,DB.[DBName]
	  ,T.[SchemaName]
	  ,a.[TableId]
	  ,T.[TableName]
	  ,a.[ColumnId]
      ,a.[ColumnName]
      ,a.[Description]
      ,a.[ColumnSortNo]
      ,a.[DataType]
      ,a.[MaxLength]
      ,a.[Precision]
      ,a.[Scale]
      ,a.[CollationName]
      ,a.[DefaultValue]
      ,a.[KeySortNo]
      ,a.[IsNullable]
      ,a.[IsOptionField]
      ,a.[FieldType]
      ,a.[IsLookupField]
      ,a.[ModifiedAt]
      ,a.[ModifiedBy]
      ,a.[Deleted]
  FROM [Setting].[Column] as a
	INNER JOIN [Setting].[Table] as T
		ON a.[TableId] = T.[TableId]
	INNER JOIN [Setting].[DB] as DB
		ON T.[DBId] =  DB.[DBId]
