USE [TADWH]
GO

/****** Object:  Table [dbo].[PurchCrMemoHdr]    Script Date: 20.01.2026 11:03:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PurchCrMemoHdr](
	[PurchCrMemoHdrId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[BuyfromVendorNo] [nvarchar](40) NOT NULL,
	[PaytoVendorNo] [nvarchar](40) NOT NULL,
	[PaytoName] [nvarchar](200) NOT NULL,
	[PaytoName2] [nvarchar](100) NOT NULL,
	[PaytoAddress] [nvarchar](200) NOT NULL,
	[PaytoAddress2] [nvarchar](100) NOT NULL,
	[PaytoCity] [nvarchar](60) NOT NULL,
	[PaytoContact] [nvarchar](200) NOT NULL,
	[YourReference] [nvarchar](70) NOT NULL,
	[ShiptoCode] [nvarchar](20) NOT NULL,
	[ShiptoName] [nvarchar](200) NOT NULL,
	[ShiptoName2] [nvarchar](100) NOT NULL,
	[ShiptoAddress] [nvarchar](200) NOT NULL,
	[ShiptoAddress2] [nvarchar](100) NOT NULL,
	[ShiptoCity] [nvarchar](60) NOT NULL,
	[ShiptoContact] [nvarchar](200) NOT NULL,
	[PostingDate] [datetime] NOT NULL,
	[ExpectedReceiptDate] [datetime] NOT NULL,
	[PostingDescription] [nvarchar](200) NOT NULL,
	[PaymentTermsCode] [nvarchar](20) NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[PaymentDiscountPct] [decimal](38, 20) NOT NULL,
	[PmtDiscountDate] [datetime] NOT NULL,
	[ShipmentMethodCode] [nvarchar](20) NOT NULL,
	[LocationCode] [nvarchar](20) NOT NULL,
	[ShortcutDimension1Code] [nvarchar](40) NOT NULL,
	[ShortcutDimension2Code] [nvarchar](40) NOT NULL,
	[VendorPostingGroup] [nvarchar](40) NOT NULL,
	[CurrencyCode] [nvarchar](20) NOT NULL,
	[CurrencyFactor] [decimal](38, 20) NOT NULL,
	[PricesIncludingVAT] [tinyint] NOT NULL,
	[InvoiceDiscCode] [nvarchar](40) NOT NULL,
	[LanguageCode] [nvarchar](20) NOT NULL,
	[PurchaserCode] [nvarchar](40) NOT NULL,
	[NoPrinted] [int] NOT NULL,
	[OnHold] [nvarchar](6) NOT NULL,
	[AppliestoDocType] [int] NOT NULL,
	[AppliestoDocNo] [nvarchar](40) NOT NULL,
	[BalAccountNo] [nvarchar](40) NOT NULL,
	[VendorCrMemoNo] [nvarchar](70) NOT NULL,
	[VATRegistrationNo] [nvarchar](40) NOT NULL,
	[SelltoCustomerNo] [nvarchar](40) NOT NULL,
	[ReasonCode] [nvarchar](20) NOT NULL,
	[GenBusPostingGroup] [nvarchar](40) NOT NULL,
	[TransactionType] [nvarchar](20) NOT NULL,
	[TransportMethod] [nvarchar](20) NOT NULL,
	[VATCountryRegionCode] [nvarchar](20) NOT NULL,
	[BuyfromVendorName] [nvarchar](200) NOT NULL,
	[BuyfromVendorName2] [nvarchar](100) NOT NULL,
	[BuyfromAddress] [nvarchar](200) NOT NULL,
	[BuyfromAddress2] [nvarchar](100) NOT NULL,
	[BuyfromCity] [nvarchar](60) NOT NULL,
	[BuyfromContact] [nvarchar](200) NOT NULL,
	[PaytoPostCode] [nvarchar](40) NOT NULL,
	[PaytoCounty] [nvarchar](60) NOT NULL,
	[PaytoCountryRegionCode] [nvarchar](20) NOT NULL,
	[BuyfromPostCode] [nvarchar](40) NOT NULL,
	[BuyfromCounty] [nvarchar](60) NOT NULL,
	[BuyfromCountryRegionCode] [nvarchar](20) NOT NULL,
	[ShiptoPostCode] [nvarchar](40) NOT NULL,
	[ShiptoCounty] [nvarchar](60) NOT NULL,
	[ShiptoCountryRegionCode] [nvarchar](20) NOT NULL,
	[BalAccountType] [int] NOT NULL,
	[OrderAddressCode] [nvarchar](20) NOT NULL,
	[EntryPoint] [nvarchar](20) NOT NULL,
	[Correction] [tinyint] NOT NULL,
	[DocumentDate] [datetime] NOT NULL,
	[Area] [nvarchar](20) NOT NULL,
	[TransactionSpecification] [nvarchar](20) NOT NULL,
	[PaymentMethodCode] [nvarchar](20) NOT NULL,
	[PreAssignedNoSeries] [nvarchar](40) NOT NULL,
	[NoSeries] [nvarchar](40) NOT NULL,
	[PreAssignedNo] [nvarchar](40) NOT NULL,
	[OrigUserID] [nvarchar](100) NOT NULL,
	[SourceCode] [nvarchar](20) NOT NULL,
	[TaxAreaCode] [nvarchar](40) NOT NULL,
	[TaxLiable] [tinyint] NOT NULL,
	[VATBusPostingGroup] [nvarchar](40) NOT NULL,
	[VATBaseDiscountPct] [decimal](38, 20) NOT NULL,
	[PrepmtCrMemoNoSeries] [nvarchar](40) NOT NULL,
	[PrepaymentCreditMemo] [tinyint] NOT NULL,
	[PrepaymentOrderNo] [nvarchar](40) NOT NULL,
	[OrigDimensionSetID] [int] NOT NULL,
	[VendorLedgerEntryNo] [int] NOT NULL,
	[CampaignNo] [nvarchar](40) NOT NULL,
	[BuyfromContactNo] [nvarchar](40) NOT NULL,
	[PaytoContactNo] [nvarchar](40) NOT NULL,
	[ResponsibilityCenter] [nvarchar](20) NOT NULL,
	[ReturnOrderNo] [nvarchar](40) NOT NULL,
	[ReturnOrderNoSeries] [nvarchar](40) NOT NULL,
	[PriceCalculationMethod] [int] NOT NULL,
	[RegistrationNo] [nvarchar](40) NOT NULL,
	[VATReportingDate] [datetime] NOT NULL,
	[FormatRegion] [nvarchar](160) NOT NULL,
	[OrigDraftCrMemoSystemId] [uniqueidentifier] NOT NULL,
	[OPPCrMemoEntranceDate] [datetime] NULL,
	[OPPPaymentBankCode] [nvarchar](40) NULL,
	[OrigOPPMandateID] [nvarchar](70) NULL,
	[OPPInstallmentTemplate] [nvarchar](20) NULL,
	[OPPInstallmentTemplateType] [int] NULL,
	[TAOrderTypeCode] [nvarchar](40) NULL,
	[TADeskOfficer] [nvarchar](40) NULL,
	[TADeliveryType] [nvarchar](20) NULL,
	[TADeliveryMonth] [datetime] NULL,
	[TACustomerOrderNumber] [nvarchar](70) NULL,
	[TAMonthOfProduction] [datetime] NULL,
	[TABLNo] [nvarchar](60) NULL,
	[TABarcode] [nvarchar](100) NULL,
	[TAWorkflowTeamDocFlow] [nvarchar](20) NULL,
	[TADocCreationUser] [nvarchar](100) NULL,
	[TAIncomingPurchaseHeaderNo] [int] NULL,
	[TALoanRedemptionDate] [datetime] NULL,
	[TALoanRedemptionReason] [nvarchar](40) NULL,
	[TALoanRedemptionCtrNo] [nvarchar](40) NULL,
	[TACtrFinancerNo] [nvarchar](40) NULL,
	[TAIsPartLoanRedemption] [tinyint] NULL,
	[TALoanRedForCredCtrDecrNo] [nvarchar](40) NULL,
	[TAShippingAgent] [nvarchar](20) NULL,
	[TAShippingAgentService] [nvarchar](20) NULL,
	[TAPackageTrackingNo] [nvarchar](60) NULL,
	[TASalesShipToPosition] [nvarchar](60) NULL,
	[TASalesShipToPositionBuilding] [nvarchar](60) NULL,
	[TASalesShipToPositionFloor] [nvarchar](60) NULL,
	[TASalesShipToPositionRoom] [nvarchar](60) NULL,
	[BuyfromVendorId] [bigint] NOT NULL,
	[PaytoVendorId] [bigint] NOT NULL,
	[PaytoAddressId] [bigint] NOT NULL,
	[ShiptoAddressId] [bigint] NOT NULL,
	[PaymentTermsId] [bigint] NOT NULL,
	[ShipmentMethodId] [bigint] NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[PurchaserId] [bigint] NOT NULL,
	[BalAccountId] [bigint] NOT NULL,
	[SelltoCustomerId] [bigint] NOT NULL,
	[ReasonCodeId] [bigint] NOT NULL,
	[GenBusinessPostingGroupId] [bigint] NOT NULL,
	[TransactionTypeId] [bigint] NOT NULL,
	[TransportMethodId] [bigint] NOT NULL,
	[VATCountryRegionId] [bigint] NOT NULL,
	[BuyfromAddressId] [bigint] NOT NULL,
	[PayToCountryRegionId] [bigint] NOT NULL,
	[BuyfromCountryRegionId] [bigint] NOT NULL,
	[ShiptoCountryRegionId] [bigint] NOT NULL,
	[AreaId] [bigint] NOT NULL,
	[PaymentMethodId] [bigint] NOT NULL,
	[SourceCodeId] [bigint] NOT NULL,
	[VATBusinessPostingGroupId] [bigint] NOT NULL,
	[VendorLedgerEntryId] [bigint] NOT NULL,
	[BuyfromContactId] [bigint] NOT NULL,
	[PaytoContactId] [bigint] NOT NULL,
	[ResponsibilityCenterId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
	[systemId] [uniqueidentifier] NULL,
	[systemCreatedAt] [datetime] NULL,
	[systemCreatedBy] [uniqueidentifier] NULL,
	[systemModifiedAt] [datetime] NULL,
	[systemModifiedBy] [uniqueidentifier] NULL,
 CONSTRAINT [pk_dbo_PurchCrMemoHdr_PurchCrMemoHdrId] PRIMARY KEY NONCLUSTERED 
(
	[PurchCrMemoHdrId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PurchCrMemoHdr] ADD  CONSTRAINT [df_dbo_PurchCrMemoHdr_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[PurchCrMemoHdr] ADD  CONSTRAINT [df_dbo_PurchCrMemoHdr_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[PurchCrMemoHdr] ADD  CONSTRAINT [df_dbo_PurchCrMemoHdr_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


