USE [TADWH]
GO

/****** Object:  Table [dbo].[SalesInvoiceHeader]    Script Date: 13.01.2026 10:53:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SalesInvoiceHeader](
	[SalesInvoiceHeaderId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[SelltoCustomerNo] [nvarchar](40) NOT NULL,
	[BilltoCustomerNo] [nvarchar](40) NOT NULL,
	[BilltoName] [nvarchar](200) NOT NULL,
	[BilltoName2] [nvarchar](100) NOT NULL,
	[BilltoAddress] [nvarchar](200) NOT NULL,
	[BilltoAddress2] [nvarchar](100) NOT NULL,
	[BilltoCity] [nvarchar](60) NOT NULL,
	[BilltoContact] [nvarchar](200) NOT NULL,
	[YourReference] [nvarchar](70) NOT NULL,
	[ShiptoCode] [nvarchar](20) NOT NULL,
	[ShiptoName] [nvarchar](200) NOT NULL,
	[ShiptoName2] [nvarchar](100) NOT NULL,
	[ShiptoAddress] [nvarchar](200) NOT NULL,
	[ShiptoAddress2] [nvarchar](100) NOT NULL,
	[ShiptoCity] [nvarchar](60) NOT NULL,
	[ShiptoContact] [nvarchar](200) NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[PostingDate] [datetime] NOT NULL,
	[ShipmentDate] [datetime] NOT NULL,
	[PostingDescription] [nvarchar](200) NOT NULL,
	[PaymentTermsCode] [nvarchar](20) NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[PaymentDiscountPct] [decimal](38, 20) NOT NULL,
	[PmtDiscountDate] [datetime] NOT NULL,
	[ShipmentMethodCode] [nvarchar](20) NOT NULL,
	[LocationCode] [nvarchar](20) NOT NULL,
	[ShortcutDimension1Code] [nvarchar](40) NOT NULL,
	[ShortcutDimension2Code] [nvarchar](40) NOT NULL,
	[CustomerPostingGroup] [nvarchar](40) NOT NULL,
	[CurrencyCode] [nvarchar](20) NOT NULL,
	[CurrencyFactor] [decimal](38, 20) NOT NULL,
	[CustomerPriceGroup] [nvarchar](20) NOT NULL,
	[PricesIncludingVAT] [tinyint] NOT NULL,
	[InvoiceDiscCode] [nvarchar](40) NOT NULL,
	[CustomerDiscGroup] [nvarchar](40) NOT NULL,
	[LanguageCode] [nvarchar](20) NOT NULL,
	[SalespersonCode] [nvarchar](40) NOT NULL,
	[OrderNo] [nvarchar](40) NOT NULL,
	[NoPrinted] [int] NOT NULL,
	[OnHold] [nvarchar](6) NOT NULL,
	[AppliestoDocType] [int] NOT NULL,
	[AppliestoDocNo] [nvarchar](40) NOT NULL,
	[BalAccountNo] [nvarchar](40) NOT NULL,
	[VATRegistrationNo] [nvarchar](40) NOT NULL,
	[ReasonCode] [nvarchar](20) NOT NULL,
	[GenBusPostingGroup] [nvarchar](40) NOT NULL,
	[EU3PartyTrade] [tinyint] NOT NULL,
	[TransactionType] [nvarchar](20) NOT NULL,
	[TransportMethod] [nvarchar](20) NOT NULL,
	[VATCountryRegionCode] [nvarchar](20) NOT NULL,
	[SelltoCustomerName] [nvarchar](200) NOT NULL,
	[SelltoCustomerName2] [nvarchar](100) NOT NULL,
	[SelltoAddress] [nvarchar](200) NOT NULL,
	[SelltoAddress2] [nvarchar](100) NOT NULL,
	[SelltoCity] [nvarchar](60) NOT NULL,
	[SelltoContact] [nvarchar](200) NOT NULL,
	[BilltoPostCode] [nvarchar](40) NOT NULL,
	[BilltoCounty] [nvarchar](60) NOT NULL,
	[BilltoCountryRegionCode] [nvarchar](20) NOT NULL,
	[SelltoPostCode] [nvarchar](40) NOT NULL,
	[SelltoCounty] [nvarchar](60) NOT NULL,
	[SelltoCountryRegionCode] [nvarchar](20) NOT NULL,
	[ShiptoPostCode] [nvarchar](40) NOT NULL,
	[ShiptoCounty] [nvarchar](60) NOT NULL,
	[ShiptoCountryRegionCode] [nvarchar](20) NOT NULL,
	[BalAccountType] [int] NOT NULL,
	[ExitPoint] [nvarchar](20) NOT NULL,
	[Correction] [tinyint] NOT NULL,
	[DocumentDate] [datetime] NOT NULL,
	[ExternalDocumentNo] [nvarchar](70) NOT NULL,
	[Area] [nvarchar](20) NOT NULL,
	[TransactionSpecification] [nvarchar](20) NOT NULL,
	[PaymentMethodCode] [nvarchar](20) NOT NULL,
	[ShippingAgentCode] [nvarchar](20) NOT NULL,
	[PackageTrackingNo] [nvarchar](60) NOT NULL,
	[PreAssignedNoSeries] [nvarchar](40) NOT NULL,
	[NoSeries] [nvarchar](40) NOT NULL,
	[OrderNoSeries] [nvarchar](40) NOT NULL,
	[PreAssignedNo] [nvarchar](40) NOT NULL,
	[OrigUserID] [nvarchar](100) NOT NULL,
	[SourceCode] [nvarchar](20) NOT NULL,
	[TaxAreaCode] [nvarchar](40) NOT NULL,
	[TaxLiable] [tinyint] NOT NULL,
	[VATBusPostingGroup] [nvarchar](40) NOT NULL,
	[VATBaseDiscountPct] [decimal](38, 20) NOT NULL,
	[InvoiceDiscountCalculation] [int] NOT NULL,
	[InvoiceDiscountValue] [decimal](38, 20) NOT NULL,
	[PrepaymentNoSeries] [nvarchar](40) NOT NULL,
	[PrepaymentInvoice] [tinyint] NOT NULL,
	[PrepaymentOrderNo] [nvarchar](40) NOT NULL,
	[QuoteNo] [nvarchar](40) NOT NULL,
	[SelltoPhoneNo] [nvarchar](60) NOT NULL,
	[SelltoEMail] [nvarchar](160) NOT NULL,
	[PaymentInstructions] [image] NULL,
	[PaymentInstructionsName] [nvarchar](40) NOT NULL,
	[PaymentReference] [nvarchar](100) NOT NULL,
	[WorkDescription] [image] NULL,
	[OrigDimensionSetID] [int] NOT NULL,
	[OrigPaymentServiceSetID] [int] NOT NULL,
	[DocumentExchangeIdentifier] [nvarchar](100) NOT NULL,
	[DocumentExchangeStatus] [int] NOT NULL,
	[DocExchOriginalIdentifier] [nvarchar](100) NOT NULL,
	[CoupledtoCRM] [tinyint] NOT NULL,
	[OrigDirectDebitMandateID] [nvarchar](70) NOT NULL,
	[CustLedgerEntryNo] [int] NOT NULL,
	[CampaignNo] [nvarchar](40) NOT NULL,
	[SelltoContactNo] [nvarchar](40) NOT NULL,
	[BilltoContactNo] [nvarchar](40) NOT NULL,
	[OpportunityNo] [nvarchar](40) NOT NULL,
	[ResponsibilityCenter] [nvarchar](20) NOT NULL,
	[PriceCalculationMethod] [int] NOT NULL,
	[AllowLineDisc] [tinyint] NOT NULL,
	[GetShipmentUsed] [tinyint] NOT NULL,
	[OrigId] [uniqueidentifier] NOT NULL,
	[OrigDraftInvoiceSystemId] [uniqueidentifier] NOT NULL,
	[systemId] [uniqueidentifier] NOT NULL,
	[systemCreatedAt] [datetime] NOT NULL,
	[systemCreatedBy] [uniqueidentifier] NOT NULL,
	[systemModifiedAt] [datetime] NOT NULL,
	[systemModifiedBy] [uniqueidentifier] NOT NULL,
	[CompanyBankAccountCode] [nvarchar](40) NOT NULL,
	[VATReportingDate] [datetime] NOT NULL,
	[FormatRegion] [nvarchar](160) NOT NULL,
	[RegistrationNumber] [nvarchar](100) NOT NULL,
	[DisputeStatus] [nvarchar](20) NOT NULL,
	[PromisedPayDate] [datetime] NOT NULL,
	[OrigDisputeStatusId] [uniqueidentifier] NOT NULL,
	[OPPPaymentBankCode] [nvarchar](40) NOT NULL,
	[OrigOPPMandateID] [nvarchar](70) NOT NULL,
	[OPPQRCode] [image] NULL,
	[OPPInstallmentTemplate] [nvarchar](20) NOT NULL,
	[OPPInstallmentTemplateType] [int] NOT NULL,
	[TAOrderType] [nvarchar](40) NOT NULL,
	[TADestination] [nvarchar](100) NOT NULL,
	[TACreateWhseShpmtAutom] [tinyint] NOT NULL,
	[TALogisticsOrderNo] [nvarchar](40) NOT NULL,
	[TADeskOfficer] [nvarchar](40) NOT NULL,
	[TAPromisedDeliveryTime] [datetime] NOT NULL,
	[TABarcode] [nvarchar](100) NOT NULL,
	[TAErrorAtRelease] [tinyint] NOT NULL,
	[TACreatedAt] [datetime] NOT NULL,
	[TADocCreationUser] [nvarchar](100) NOT NULL,
	[TAInternalCustPriceGroup] [nvarchar](20) NOT NULL,
	[TACreditLimitCheckActive] [tinyint] NOT NULL,
	[TAServiceItemNo] [nvarchar](40) NOT NULL,
	[TAContractNo] [nvarchar](40) NOT NULL,
	[TAShipToPosition] [nvarchar](60) NOT NULL,
	[TAShipToPositionBuilding] [nvarchar](60) NOT NULL,
	[TAShipToPositionFloor] [nvarchar](60) NOT NULL,
	[TAShipToPositionRoom] [nvarchar](60) NOT NULL,
	[TASourceDocumentNo] [nvarchar](40) NOT NULL,
	[TANoOfRelatedSalesOrders] [int] NOT NULL,
	[TANoOfRelatedServiceOrders] [int] NOT NULL,
	[TANoOfRelatedSalesQuotes] [int] NOT NULL,
	[TAPublicSectorProofSubmitted] [datetime] NOT NULL,
	[TAPromotionProject] [tinyint] NOT NULL,
	[TAProjectQuoteNo] [nvarchar](40) NOT NULL,
	[TABlocked] [tinyint] NOT NULL,
	[TAProjectStartingDate] [datetime] NOT NULL,
	[TAProjectEndingDate] [datetime] NOT NULL,
	[TAProjectDescription] [nvarchar](400) NOT NULL,
	[TAPostalInvoiceRecipientCode] [nvarchar](20) NOT NULL,
	[TAName] [nvarchar](200) NOT NULL,
	[TAName2] [nvarchar](100) NOT NULL,
	[TAAddress] [nvarchar](200) NOT NULL,
	[TAAddress2] [nvarchar](100) NOT NULL,
	[TACity] [nvarchar](60) NOT NULL,
	[TAPostCode] [nvarchar](40) NOT NULL,
	[TACountryRegionCode] [nvarchar](20) NOT NULL,
	[TACounty] [nvarchar](60) NOT NULL,
	[TAContact] [nvarchar](200) NOT NULL,
	[TAShipToPostalEmail] [nvarchar](160) NOT NULL,
	[TACombineShipmentVBM] [tinyint] NOT NULL,
	[TADistributionChannel] [nvarchar](40) NOT NULL,
	[TAWorkpackageNo] [nvarchar](40) NOT NULL,
	[TAActivityCode] [nvarchar](40) NOT NULL,
	[TANoProformaInvPrinted] [int] NOT NULL,
	[TAWorkflowTeamDocFlow] [nvarchar](20) NOT NULL,
	[TACustPurchaseOrderNo] [nvarchar](40) NOT NULL,
	[TALastBlanketOrderUpdate] [datetime] NOT NULL,
	[TATechnician] [nvarchar](40) NOT NULL,
	[TADamageReturnOrderNo] [nvarchar](40) NOT NULL,
	[TAContractBilling] [tinyint] NOT NULL,
	[TAContractDocLayout] [int] NOT NULL,
	[TAContractDocAppendixDetails] [int] NOT NULL,
	[TACtrAppliesToDocType] [int] NOT NULL,
	[TACtrAppliesToDocNo] [nvarchar](40) NOT NULL,
	[TAXRechnung] [tinyint] NOT NULL,
	[TAInterfacePartnerNo] [nvarchar](40) NOT NULL,
	[TANoOfExpInvPrinted] [int] NOT NULL,
	[TAExternalNo] [nvarchar](100) NOT NULL,
	[TAReopenedFromWarehouse] [tinyint] NOT NULL,
	[TAFullReservationRequired] [tinyint] NOT NULL,
	[CMNM4TAZeroAmtMailSuppressed] [tinyint] NOT NULL,
	[TAVendorShipmentNo] [nvarchar](70) NOT NULL,
	[TAFSMOrderNo] [nvarchar](70) NOT NULL,
	[CCSITTCountryofOriginCode] [nvarchar](20) NOT NULL,
	[CCSITTRecipientCountryCode] [nvarchar](20) NOT NULL,
	[CCSITTOurVATRegNo] [nvarchar](40) NOT NULL,
	[TAShippingAgentServiceCode] [nvarchar](20) NOT NULL,
	[SelltoCustomerId] [bigint] NOT NULL,
	[BilltoCustomerId] [bigint] NOT NULL,
	[BilltoAddressId] [bigint] NOT NULL,
	[ShiptoAddressId] [bigint] NOT NULL,
	[PaymentTermsId] [bigint] NOT NULL,
	[ShipmentMethodId] [bigint] NOT NULL,
	[LocationId] [bigint] NOT NULL,
	[CustomerPostingGroupId] [bigint] NOT NULL,
	[CurrencyId] [bigint] NOT NULL,
	[CustomerPriceGroupId] [bigint] NOT NULL,
	[CustInvoiceDiscId] [bigint] NOT NULL,
	[CustomerDiscountGroupId] [bigint] NOT NULL,
	[SalespersonId] [bigint] NOT NULL,
	[BalAccountId] [bigint] NOT NULL,
	[ReasonCodeId] [bigint] NOT NULL,
	[GenBusinessPostingGroupId] [bigint] NOT NULL,
	[TransactionTypeId] [bigint] NOT NULL,
	[TransportMethodId] [bigint] NOT NULL,
	[VATCountryRegionId] [bigint] NOT NULL,
	[SelltoAddressId] [bigint] NOT NULL,
	[BilltoCountryRegionId] [bigint] NOT NULL,
	[SelltoCountryRegionId] [bigint] NOT NULL,
	[ShiptoCountryRegionId] [bigint] NOT NULL,
	[AreaId] [bigint] NOT NULL,
	[PaymentMethodId] [bigint] NOT NULL,
	[SourceCodeId] [bigint] NOT NULL,
	[VATBusinessPostingGroupId] [bigint] NOT NULL,
	[CustLedgerEntryId] [bigint] NOT NULL,
	[CampaignId] [bigint] NOT NULL,
	[SelltoContactId] [bigint] NOT NULL,
	[ResponsibilityCenterId] [bigint] NOT NULL,
	[TAContractHeaderId] [bigint] NOT NULL,
	[TADistributionChannelId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
 CONSTRAINT [pk_dbo_SalesInvoiceHeader_SalesInvoiceHeaderId] PRIMARY KEY NONCLUSTERED 
(
	[SalesInvoiceHeaderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SalesInvoiceHeader] ADD  CONSTRAINT [df_dbo_SalesInvoiceHeader_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[SalesInvoiceHeader] ADD  CONSTRAINT [df_dbo_SalesInvoiceHeader_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[SalesInvoiceHeader] ADD  CONSTRAINT [df_dbo_SalesInvoiceHeader_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


