USE [TADWH]
GO

/****** Object:  Table [dbo].[ServiceItem]    Script Date: 13.01.2026 10:55:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ServiceItem](
	[ServiceItemId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[SerialNo] [nvarchar](100) NOT NULL,
	[ServiceItemGroupCode] [nvarchar](20) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Description2] [nvarchar](100) NOT NULL,
	[Status] [int] NOT NULL,
	[Priority] [int] NOT NULL,
	[CustomerNo] [nvarchar](40) NOT NULL,
	[ShiptoCode] [nvarchar](20) NOT NULL,
	[ItemNo] [nvarchar](40) NOT NULL,
	[UnitofMeasureCode] [nvarchar](20) NOT NULL,
	[LocationofServiceItem] [nvarchar](60) NOT NULL,
	[SalesUnitPrice] [decimal](38, 20) NOT NULL,
	[SalesUnitCost] [decimal](38, 20) NOT NULL,
	[WarrantyStartingDateLabor] [datetime] NOT NULL,
	[WarrantyEndingDateLabor] [datetime] NOT NULL,
	[WarrantyStartingDateParts] [datetime] NOT NULL,
	[WarrantyEndingDateParts] [datetime] NOT NULL,
	[WarrantyPctParts] [decimal](38, 20) NOT NULL,
	[WarrantyPctLabor] [decimal](38, 20) NOT NULL,
	[ResponseTimeHours] [decimal](38, 20) NOT NULL,
	[InstallationDate] [datetime] NOT NULL,
	[SalesDate] [datetime] NOT NULL,
	[LastServiceDate] [datetime] NOT NULL,
	[DefaultContractValue] [decimal](38, 20) NOT NULL,
	[DefaultContractDiscountPct] [decimal](38, 20) NOT NULL,
	[VendorNo] [nvarchar](40) NOT NULL,
	[VendorItemNo] [nvarchar](100) NOT NULL,
	[NoSeries] [nvarchar](40) NOT NULL,
	[VendorItemName] [nvarchar](200) NOT NULL,
	[PreferredResource] [nvarchar](40) NOT NULL,
	[VariantCode] [nvarchar](20) NOT NULL,
	[ServicePriceGroupCode] [nvarchar](20) NOT NULL,
	[DefaultContractCost] [decimal](38, 20) NOT NULL,
	[SearchDescription] [nvarchar](200) NOT NULL,
	[SalesServShptDocumentNo] [nvarchar](40) NOT NULL,
	[SalesServShptLineNo] [int] NOT NULL,
	[ShipmentType] [int] NOT NULL,
	[Blocked] [int] NOT NULL,
	[TABuilding] [nvarchar](60) NULL,
	[TAFloor] [nvarchar](60) NULL,
	[TARoom] [nvarchar](60) NULL,
	[TABlocked] [tinyint] NULL,
	[TACategory] [nvarchar](20) NULL,
	[TAExternalNo] [nvarchar](100) NULL,
	[TAShipmentDate] [datetime] NULL,
	[TAUsed] [tinyint] NULL,
	[TAReLife] [tinyint] NULL,
	[TACustomerCostCenterInfo] [nvarchar](100) NULL,
	[TACustomerInfo1] [nvarchar](100) NULL,
	[TACustomerInfo2] [nvarchar](100) NULL,
	[TACustomerInfo3] [nvarchar](100) NULL,
	[TAInterfaceTimestamp] [datetime] NULL,
	[TAOldNo] [nvarchar](40) NULL,
	[TAConstructionYear] [datetime] NULL,
	[TANetworkHostIPAddress] [nvarchar](30) NULL,
	[TANetworkSubnetMask] [nvarchar](30) NULL,
	[TANetworkStdGatewayIPAddress] [nvarchar](30) NULL,
	[TAMACAddress] [nvarchar](46) NULL,
	[TACommunicationType] [int] NULL,
	[TAServiceDeliveryType] [int] NULL,
	[TASupervisingCompany] [nvarchar](40) NULL,
	[TAServiceLock] [int] NULL,
	[TALockedForVBM] [tinyint] NULL,
	[TAVBMShipToCode] [nvarchar](40) NULL,
	[TAManagedByKFS] [tinyint] NULL,
	[TARelevantForFSM] [tinyint] NULL,
	[TAManufacturerNo] [nvarchar](20) NULL,
	[TAWarehouseReceipt] [nvarchar](40) NULL,
	[TAPayToVendorNo] [nvarchar](100) NULL,
	[TAPurchInvoice] [nvarchar](100) NULL,
	[TAPurchInvoiceDate] [datetime] NULL,
	[TAHistUnitCost] [decimal](38, 20) NULL,
	[TAUnitCost] [decimal](38, 20) NULL,
	[TAWarehouseShipmentDate] [datetime] NULL,
	[TAWarehouseShipment] [nvarchar](40) NULL,
	[TASellToCustNo] [nvarchar](40) NULL,
	[TASalesInvoiceNo] [nvarchar](40) NULL,
	[TASalesInvoiceDate] [datetime] NULL,
	[TAHistSalesPrice] [decimal](38, 20) NULL,
	[TASalesPrice] [decimal](38, 20) NULL,
	[TAListPrice] [decimal](38, 20) NULL,
	[TAContactNo] [nvarchar](40) NULL,
	[TABlockingReasonCode] [nvarchar](20) NULL,
	[TABlockingReasonDescription] [nvarchar](200) NULL,
	[TABaseCalenderCode] [nvarchar](20) NULL,
	[TAGlobProjectNo] [nvarchar](40) NULL,
	[TAGlobalProjectLineNo] [int] NULL,
	[TALicenseKey] [nvarchar](100) NULL,
	[TAPitchName] [nvarchar](200) NULL,
	[TAPitchName2] [nvarchar](100) NULL,
	[TAPitchAddress] [nvarchar](200) NULL,
	[TAPitchAddress2] [nvarchar](100) NULL,
	[TAPitchCity] [nvarchar](60) NULL,
	[TAPitchPostCode] [nvarchar](40) NULL,
	[TAPitchCounty] [nvarchar](60) NULL,
	[TAPitchCountryRegionCode] [nvarchar](20) NULL,
	[TAPitchContactPhoneNo] [nvarchar](60) NULL,
	[TAPitchContactEmail] [nvarchar](160) NULL,
	[TAPitchContactName] [nvarchar](200) NULL,
	[TAOwnership] [int] NULL,
	[TAThirdParty] [tinyint] NULL,
	[TAServiceEmail] [nvarchar](160) NULL,
	[TAResolutionBlockingReason] [nvarchar](160) NULL,
	[TAServiceItemBin] [nvarchar](40) NULL,
	[TATotalNetweight] [decimal](38, 20) NULL,
	[TAProfessionalServicesmLog] [tinyint] NULL,
	[ServiceItemGroupId] [bigint] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[ItemId] [bigint] NOT NULL,
	[UnitofMeasureId] [bigint] NOT NULL,
	[VendorId] [bigint] NOT NULL,
	[TAServiceItemCaegoryId] [bigint] NOT NULL,
	[TAServiceStatusEmail] [nvarchar](160) NULL,
	[TAActiveServiceContract] [nvarchar](40) NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
	[systemId] [uniqueidentifier] NULL,
	[systemCreatedAt] [datetime] NULL,
	[systemCreatedBy] [uniqueidentifier] NULL,
	[systemModifiedAt] [datetime] NULL,
	[systemModifiedBy] [uniqueidentifier] NULL,
 CONSTRAINT [pk_dbo_ServiceItem_ServiceItemId] PRIMARY KEY NONCLUSTERED 
(
	[ServiceItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ServiceItem] ADD  CONSTRAINT [df_dbo_ServiceItem_ModifiedA]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[ServiceItem] ADD  CONSTRAINT [df_dbo_ServiceItem_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[ServiceItem] ADD  CONSTRAINT [df_dbo_ServiceItem_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


