USE [TADWH]
GO

/****** Object:  Table [dbo].[Item]    Script Date: 13.01.2026 10:55:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Item](
	[ItemId] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[No] [nvarchar](40) NOT NULL,
	[No2] [nvarchar](40) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[SearchDescription] [nvarchar](200) NOT NULL,
	[Description2] [nvarchar](100) NOT NULL,
	[BaseUnitofMeasure] [nvarchar](20) NOT NULL,
	[PriceUnitConversion] [int] NOT NULL,
	[Type] [int] NOT NULL,
	[InventoryPostingGroup] [nvarchar](40) NOT NULL,
	[ShelfNo] [nvarchar](20) NOT NULL,
	[ItemDiscGroup] [nvarchar](40) NOT NULL,
	[AllowInvoiceDisc] [tinyint] NOT NULL,
	[StatisticsGroup] [int] NOT NULL,
	[CommissionGroup] [int] NOT NULL,
	[UnitPrice] [decimal](38, 20) NOT NULL,
	[PriceProfitCalculation] [int] NOT NULL,
	[ProfitPct] [decimal](38, 20) NOT NULL,
	[CostingMethod] [int] NOT NULL,
	[UnitCost] [decimal](38, 20) NOT NULL,
	[StandardCost] [decimal](38, 20) NOT NULL,
	[LastDirectCost] [decimal](38, 20) NOT NULL,
	[IndirectCostPct] [decimal](38, 20) NOT NULL,
	[CostisAdjusted] [tinyint] NOT NULL,
	[AllowOnlineAdjustment] [tinyint] NOT NULL,
	[VendorNo] [nvarchar](40) NOT NULL,
	[VendorItemNo] [nvarchar](100) NOT NULL,
	[LeadTimeCalculation] [nvarchar](32) NOT NULL,
	[ReorderPoint] [decimal](38, 20) NOT NULL,
	[MaximumInventory] [decimal](38, 20) NOT NULL,
	[ReorderQuantity] [decimal](38, 20) NOT NULL,
	[AlternativeItemNo] [nvarchar](40) NOT NULL,
	[UnitListPrice] [decimal](38, 20) NOT NULL,
	[DutyDuePct] [decimal](38, 20) NOT NULL,
	[DutyCode] [nvarchar](20) NOT NULL,
	[GrossWeight] [decimal](38, 20) NOT NULL,
	[NetWeight] [decimal](38, 20) NOT NULL,
	[UnitsperParcel] [decimal](38, 20) NOT NULL,
	[UnitVolume] [decimal](38, 20) NOT NULL,
	[Durability] [nvarchar](20) NOT NULL,
	[FreightType] [nvarchar](20) NOT NULL,
	[TariffNo] [nvarchar](40) NOT NULL,
	[DutyUnitConversion] [decimal](38, 20) NOT NULL,
	[CountryRegionPurchasedCode] [nvarchar](20) NOT NULL,
	[BudgetQuantity] [decimal](38, 20) NOT NULL,
	[BudgetedAmount] [decimal](38, 20) NOT NULL,
	[BudgetProfit] [decimal](38, 20) NOT NULL,
	[Blocked] [tinyint] NOT NULL,
	[BlockReason] [nvarchar](500) NOT NULL,
	[LastDateTimeModified] [datetime] NOT NULL,
	[LastDateModified] [datetime] NOT NULL,
	[LastTimeModified] [datetime] NOT NULL,
	[PriceIncludesVAT] [tinyint] NOT NULL,
	[VATBusPostingGrPrice] [nvarchar](40) NOT NULL,
	[GenProdPostingGroup] [nvarchar](40) NOT NULL,
	[Picture] [uniqueidentifier] NOT NULL,
	[CountryRegionofOriginCode] [nvarchar](20) NOT NULL,
	[AutomaticExtTexts] [tinyint] NOT NULL,
	[NoSeries] [nvarchar](40) NOT NULL,
	[TaxGroupCode] [nvarchar](40) NOT NULL,
	[VATProdPostingGroup] [nvarchar](40) NOT NULL,
	[Reserve] [int] NOT NULL,
	[GlobalDimension1Code] [nvarchar](40) NOT NULL,
	[GlobalDimension2Code] [nvarchar](40) NOT NULL,
	[StockoutWarning] [int] NOT NULL,
	[PreventNegativeInventory] [int] NOT NULL,
	[OrigApplicationWkshUserID] [nvarchar](256) NOT NULL,
	[AssemblyPolicy] [int] NOT NULL,
	[GTIN] [nvarchar](28) NOT NULL,
	[DefaultDeferralTemplateCode] [nvarchar](20) NOT NULL,
	[LowLevelCode] [int] NOT NULL,
	[LotSize] [decimal](38, 20) NOT NULL,
	[SerialNos] [nvarchar](40) NOT NULL,
	[LastUnitCostCalcDate] [datetime] NOT NULL,
	[RolledupMaterialCost] [decimal](38, 20) NOT NULL,
	[RolledupCapacityCost] [decimal](38, 20) NOT NULL,
	[ScrapPct] [decimal](38, 20) NOT NULL,
	[InventoryValueZero] [tinyint] NOT NULL,
	[DiscreteOrderQuantity] [int] NOT NULL,
	[MinimumOrderQuantity] [decimal](38, 20) NOT NULL,
	[MaximumOrderQuantity] [decimal](38, 20) NOT NULL,
	[SafetyStockQuantity] [decimal](38, 20) NOT NULL,
	[OrderMultiple] [decimal](38, 20) NOT NULL,
	[SafetyLeadTime] [nvarchar](32) NOT NULL,
	[FlushingMethod] [int] NOT NULL,
	[ReplenishmentSystem] [int] NOT NULL,
	[RoundingPrecision] [decimal](38, 20) NOT NULL,
	[SalesUnitofMeasure] [nvarchar](20) NOT NULL,
	[PurchUnitofMeasure] [nvarchar](20) NOT NULL,
	[TimeBucket] [nvarchar](32) NOT NULL,
	[ReorderingPolicy] [int] NOT NULL,
	[IncludeInventory] [tinyint] NOT NULL,
	[ManufacturingPolicy] [int] NOT NULL,
	[ReschedulingPeriod] [nvarchar](32) NOT NULL,
	[LotAccumulationPeriod] [nvarchar](32) NOT NULL,
	[DampenerPeriod] [nvarchar](32) NOT NULL,
	[DampenerQuantity] [decimal](38, 20) NOT NULL,
	[OverflowLevel] [decimal](38, 20) NOT NULL,
	[ManufacturerCode] [nvarchar](20) NOT NULL,
	[ItemCategoryCode] [nvarchar](40) NOT NULL,
	[CreatedFromNonstockItem] [tinyint] NOT NULL,
	[ProductGroupCode] [nvarchar](20) NOT NULL,
	[PurchasingCode] [nvarchar](20) NOT NULL,
	[ServiceItemGroup] [nvarchar](20) NOT NULL,
	[ItemTrackingCode] [nvarchar](20) NOT NULL,
	[LotNos] [nvarchar](40) NOT NULL,
	[ExpirationCalculation] [nvarchar](32) NOT NULL,
	[WarehouseClassCode] [nvarchar](20) NOT NULL,
	[SpecialEquipmentCode] [nvarchar](20) NOT NULL,
	[PutawayTemplateCode] [nvarchar](20) NOT NULL,
	[PutawayUnitofMeasureCode] [nvarchar](20) NOT NULL,
	[PhysInvtCountingPeriodCode] [nvarchar](20) NOT NULL,
	[LastCountingPeriodUpdate] [datetime] NOT NULL,
	[UseCrossDocking] [tinyint] NOT NULL,
	[NextCountingStartDate] [datetime] NOT NULL,
	[NextCountingEndDate] [datetime] NOT NULL,
	[OrigId] [uniqueidentifier] NOT NULL,
	[OrigUnitofMeasureId] [uniqueidentifier] NOT NULL,
	[OrigTaxGroupId] [uniqueidentifier] NOT NULL,
	[SalesBlocked] [tinyint] NOT NULL,
	[PurchasingBlocked] [tinyint] NOT NULL,
	[OrigItemCategoryId] [uniqueidentifier] NOT NULL,
	[OverReceiptCode] [nvarchar](40) NOT NULL,
	[RoutingNo] [nvarchar](40) NOT NULL,
	[ProductionBOMNo] [nvarchar](40) NOT NULL,
	[SingleLevelMaterialCost] [decimal](38, 20) NOT NULL,
	[SingleLevelCapacityCost] [decimal](38, 20) NOT NULL,
	[SingleLevelSubcontrdCost] [decimal](38, 20) NOT NULL,
	[SingleLevelCapOvhdCost] [decimal](38, 20) NOT NULL,
	[SingleLevelMfgOvhdCost] [decimal](38, 20) NOT NULL,
	[OverheadRate] [decimal](38, 20) NOT NULL,
	[RolledupSubcontractedCost] [decimal](38, 20) NOT NULL,
	[RolledupMfgOvhdCost] [decimal](38, 20) NOT NULL,
	[RolledupCapOverheadCost] [decimal](38, 20) NOT NULL,
	[OrderTrackingPolicy] [int] NOT NULL,
	[Critical] [tinyint] NOT NULL,
	[CommonItemNo] [nvarchar](40) NOT NULL,
	[systemId] [uniqueidentifier] NOT NULL,
	[systemCreatedAt] [datetime] NOT NULL,
	[systemCreatedBy] [uniqueidentifier] NOT NULL,
	[systemModifiedAt] [datetime] NOT NULL,
	[systemModifiedBy] [uniqueidentifier] NOT NULL,
	[VariantMandatoryifExists] [int] NOT NULL,
	[CoupledtoCRM] [tinyint] NOT NULL,
	[OrigInventoryPostingGroupId] [uniqueidentifier] NOT NULL,
	[OrigGenProdPostingGroupId] [uniqueidentifier] NOT NULL,
	[ExcludedfromCostAdjustment] [tinyint] NOT NULL,
	[ServiceBlocked] [tinyint] NOT NULL,
	[TADisposalLumpSumInPercentage] [decimal](38, 20) NOT NULL,
	[TASuccessorItemNo] [nvarchar](40) NOT NULL,
	[TACopyrightFeeAmountBase] [decimal](38, 20) NOT NULL,
	[TAKDCProductHierarchy] [nvarchar](32) NOT NULL,
	[TAKDCProductGroup] [nvarchar](18) NOT NULL,
	[TAKDCMaterialType] [nvarchar](20) NOT NULL,
	[TAClassification] [nvarchar](20) NOT NULL,
	[TAParentItemCategoryCode] [nvarchar](40) NOT NULL,
	[TAManufacturerItemNo] [nvarchar](40) NOT NULL,
	[TAModelCode] [nvarchar](40) NOT NULL,
	[TAModelRelations] [nvarchar](500) NOT NULL,
	[TATiltIndicatorNecessary] [tinyint] NOT NULL,
	[TACustomesTariffNo] [nvarchar](40) NOT NULL,
	[TALongLifeItem] [tinyint] NOT NULL,
	[TAEpedemic] [tinyint] NOT NULL,
	[TAFastMovingItem] [tinyint] NOT NULL,
	[TAReturnPart] [tinyint] NOT NULL,
	[TAPSICode] [nvarchar](40) NOT NULL,
	[TAPSISorting] [int] NOT NULL,
	[TAAltShelfNo] [nvarchar](20) NOT NULL,
	[TABeConsolidated] [tinyint] NOT NULL,
	[TANoCEPShipping] [tinyint] NOT NULL,
	[TAProductionStartingDate] [datetime] NOT NULL,
	[TAProductionEndingDate] [datetime] NOT NULL,
	[TAStartOfSale] [datetime] NOT NULL,
	[TAEndOfSales] [datetime] NOT NULL,
	[TAReferenceOperPerformance] [int] NOT NULL,
	[TAOperationalPerformance] [int] NOT NULL,
	[TAOperationalPerformanceUnit] [nvarchar](20) NOT NULL,
	[TAAbsorbancePercent] [decimal](38, 20) NOT NULL,
	[TABoLUnitOfMeasureCode] [nvarchar](20) NOT NULL,
	[TABrandCode] [nvarchar](40) NOT NULL,
	[TAVBMServiceOrder] [tinyint] NOT NULL,
	[TAWorkingTimeInMinutes] [int] NOT NULL,
	[TAMeterReadingInformationCode] [nvarchar](20) NOT NULL,
	[TAPlanningForPSI] [tinyint] NOT NULL,
	[TAPlanningForKMPSI] [tinyint] NOT NULL,
	[TAProdShipmentInMonths] [decimal](38, 20) NOT NULL,
	[TADelTimeAvailableInMonth] [decimal](38, 20) NOT NULL,
	[TALawType] [int] NOT NULL,
	[TABusinessRelation] [int] NOT NULL,
	[TADisposalCategoryCode] [nvarchar](40) NOT NULL,
	[TAFSMItemCategory] [int] NOT NULL,
	[TAFSMReplaceAlways] [tinyint] NOT NULL,
	[TAItemType] [nvarchar](40) NOT NULL,
	[TACatalogItemEntryNo] [nvarchar](40) NOT NULL,
	[TAOldItemNo] [nvarchar](40) NOT NULL,
	[TAMinStockAvarage] [int] NOT NULL,
	[TAPercentfromSalesQty] [decimal](38, 20) NOT NULL,
	[TACreationUser] [nvarchar](100) NOT NULL,
	[TAModificationUser] [nvarchar](100) NOT NULL,
	[TAWorkflowTeam] [nvarchar](20) NOT NULL,
	[TARequestEntryNo] [int] NOT NULL,
	[TAIndependantColli] [tinyint] NOT NULL,
	[TADemandByPCCHandLoc] [tinyint] NOT NULL,
	[TAPurchOrderByAllocPlan] [tinyint] NOT NULL,
	[TAStandAloneService] [int] NOT NULL,
	[TARecommendedUnitPrice] [decimal](38, 20) NOT NULL,
	[TAMinimumUnitPrice] [decimal](38, 20) NOT NULL,
	[TACatalogPriceInfo] [decimal](38, 20) NOT NULL,
	[TAActivityCode] [nvarchar](40) NOT NULL,
	[TAObjectClassCode] [nvarchar](40) NOT NULL,
	[TAInterfaceTimestamp] [datetime] NOT NULL,
	[TAWkfStatus] [int] NOT NULL,
	[TALocationCode] [nvarchar](40) NOT NULL,
	[HasSalesForecast] [tinyint] NOT NULL,
	[ExcludefromIntrastatReport] [tinyint] NOT NULL,
	[SupplementaryUnitofMeasure] [nvarchar](20) NOT NULL,
	[TAMDMLastTimeReleased] [datetime] NOT NULL,
	[TAArchiving] [tinyint] NOT NULL,
	[TAKDEMItemUsage] [int] NOT NULL,
	[BaseUnitofMeasureId] [bigint] NOT NULL,
	[InventoryPostingGroupId] [bigint] NOT NULL,
	[ItemDiscountGroupId] [bigint] NOT NULL,
	[VendorId] [bigint] NOT NULL,
	[CountryRegionPurchasedId] [bigint] NOT NULL,
	[VATBusPostingGrPriceId] [bigint] NOT NULL,
	[GenProdPostingGroupId] [bigint] NOT NULL,
	[CountryRegionofOriginId] [bigint] NOT NULL,
	[VATProductPostingGroupId] [bigint] NOT NULL,
	[SalesUnitofMeasureId] [bigint] NOT NULL,
	[PurchUnitofMeasureId] [bigint] NOT NULL,
	[ItemCategoryId] [bigint] NOT NULL,
	[ProductGroupId] [bigint] NOT NULL,
	[ServiceItemGroupId] [bigint] NOT NULL,
	[ItemTrackingCodeId] [bigint] NOT NULL,
	[TABrandId] [bigint] NOT NULL,
	[TAMeterReadingInformationHdrId] [bigint] NOT NULL,
	[ModifiedAt] [datetime] NULL,
	[ModifiedBy] [sysname] NOT NULL,
	[Deleted] [tinyint] NULL,
 CONSTRAINT [pk_dbo_Item_ItemId] PRIMARY KEY NONCLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Item] ADD  CONSTRAINT [df_dbo_Item_ModifiedAt]  DEFAULT (getdate()) FOR [ModifiedAt]
GO

ALTER TABLE [dbo].[Item] ADD  CONSTRAINT [df_dbo_Item_ModifiedBy]  DEFAULT ('SYSTEM') FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[Item] ADD  CONSTRAINT [df_dbo_Item_Deleted]  DEFAULT ((0)) FOR [Deleted]
GO


